`use strict`

 export const insert_TB_COR_TALK_ITEM_MST_01 = 
`INSERT INTO BRUNNER.TB_COR_TALK_ITEM_MST
  (SYSTEM_CODE, TALK_ID, TALK_USER_ID, TALK_TITLE, TALK_CONTENT,
  TALK_CATEGORY_ID, PARENT_TALK_ID)
 VALUES (
  ?, ?, ?, ?, ?, 
  ?, NULL
 )
 `
 ;

 export const update_TB_COR_TALK_ITEM_MST_01 = 
 `UPDATE BRUNNER.TB_COR_TALK_ITEM_MST
     SET TALK_TITLE = ?,
         TALK_CONTENT = ?
   WHERE SYSTEM_CODE = ? 
     AND TALK_ID = ?
  `
  ;
 
  export const select_TB_COR_TALK_ITEM_MST_01 = 
`SELECT TI.SYSTEM_CODE, TI.TALK_ID, TI.TALK_USER_ID, TI.TALK_TITLE, TI.TALK_CONTENT,
        TI.TALK_CATEGORY_ID, TC.CATEGORY_NAME, TI.PARENT_TALK_ID
  FROM BRUNNER.TB_COR_TALK_ITEM_MST TI
 INNER JOIN BRUNNER.TB_COR_TALK_CATEGORY_MST TC
    ON TC.SYSTEM_CODE=TI.SYSTEM_CODE
   AND TC.CATEGORY_ID=TI.TALK_CATEGORY_ID
 WHERE TI.SYSTEM_CODE = ?
   AND TI.TALK_CATEGORY_ID = ?
   AND TI.TALK_ID < ?
 ORDER BY TI.TALK_ID DESC
 LIMIT 0,?
 `
 ;
