`use strict`

 export const insert_TB_COR_TALK_ITEM_MST_01 = 
`INSERT INTO BRUNNER.TB_COR_TALK_ITEM_MST
  (SYSTEM_CODE, TALK_ID, TALK_USER_ID, TALK_TITLE, TALK_CONTENT,
  TALK_CATEGORY, PARENT_TALK_ID)
 VALUES (
  ?, ?, ?, ?, ?, 
  ?, NULL
 )
 `
 ;

 export const update_TB_COR_TALK_ITEM_MST_01 = 
 `UPDATE BRUNNER.TB_COR_TALK_ITEM_MST
     SET TALK_TITLE = ?,
         TALK_CONTENT = ?
   WHERE SYSTEM_CODE = ? 
     AND TALK_ID = ?
  `
  ;
 
  export const select_TB_COR_TALK_ITEM_MST_01 = 
`SELECT SYSTEM_CODE, TALK_ID, TALK_USER_ID, TALK_TITLE, TALK_CONTENT,
        TALK_CATEGORY, PARENT_TALK_ID
  FROM BRUNNER.TB_COR_TALK_ITEM_MST
 WHERE SYSTEM_CODE = ?
   AND TALK_CATEGORY = ?
   AND TALK_ID < ?
 ORDER BY TALK_ID DESC
 LIMIT 0,?
 `
 ;
