`use strict`

export const insert_TB_COR_TALK_ITEM_MST_01 =
  `INSERT INTO BRUNNER.TB_COR_TALK_ITEM_MST
  (SYSTEM_CODE, TALK_ITEM_ID, TALK_ITEM_USER_ID, TALK_ITEM_TITLE, TALK_ITEM_CONTENT,
  TALK_ID, PARENT_TALK_ITEM_ID)
 VALUES (
  ?, ?, ?, ?, ?, 
  ?, NULL
 )
 `
  ;

export const update_TB_COR_TALK_ITEM_MST_01 =
  `UPDATE BRUNNER.TB_COR_TALK_ITEM_MST
     SET TALK_ITEM_TITLE = ?,
         TALK_ITEM_CONTENT = ?
   WHERE SYSTEM_CODE = ? 
     AND TALK_ITEM_ID = ?
  `
  ;

export const select_TB_COR_TALK_ITEM_MST_01 =
  `SELECT TI.SYSTEM_CODE, TI.TALK_ITEM_ID, TI.TALK_ITEM_USER_ID, TI.TALK_ITEM_TITLE, TI.TALK_ITEM_CONTENT,
        TM.TALK_ID, TM.TALK_NAME, TI.PARENT_TALK_ITEM_ID
  FROM BRUNNER.TB_COR_TALK_ITEM_MST TI
 INNER JOIN BRUNNER.TB_COR_TALK_MST TM
    ON TM.SYSTEM_CODE=TI.SYSTEM_CODE
   AND TM.TALK_ID=TI.TALK_ID
 WHERE TI.SYSTEM_CODE = ?
   AND TI.TALK_ID = ?
   AND TI.TALK_ITEM_ID < ?
 ORDER BY TI.TALK_ITEM_ID DESC
 LIMIT 0,?
 `
  ;

export const select_TB_COR_TALK_ITEM_MST_02 =
  `
  SELECT DISTINCT A.TO_USER_ID
    FROM (
  SELECT DISTINCT TIM.SYSTEM_CODE, TIM2.TALK_ITEM_USER_ID TO_USER_ID
   FROM BRUNNER.TB_COR_TALK_ITEM_MST TIM
  INNER JOIN BRUNNER.TB_COR_TALK_ITEM_MST TIM2
     ON TIM2.SYSTEM_CODE = TIM.SYSTEM_CODE
    AND TIM2.TALK_ID = TIM.TALK_ID
    AND TIM2.TALK_ITEM_USER_ID <> TIM.TALK_ITEM_USER_ID
  WHERE TIM.SYSTEM_CODE = ?
    AND TIM.TALK_ITEM_ID = ?
  UNION ALL
  SELECT TM.SYSTEM_CODE, TM.CREATE_USER_ID TO_USER_ID
    FROM BRUNNER.TB_COR_TALK_ITEM_MST TIM
  INNER JOIN BRUNNER.TB_COR_TALK_MST TM
     ON TM.SYSTEM_CODE = TIM.SYSTEM_CODE
    AND TM.TALK_ID = TIM.TALK_ID
    AND TM.CREATE_USER_ID <> TIM.TALK_ITEM_USER_ID
   WHERE TIM.SYSTEM_CODE = ?
    AND TIM.TALK_ITEM_ID = ?) A
 `
  ;
