`use strict`

export const insert_TB_COR_TALK_MST_01 =
  `INSERT INTO BRUNNER.TB_COR_TALK_MST
 (SYSTEM_CODE, TALK_ID, TALK_NAME, CREATE_USER_ID, CREATE_TIME) VALUES
 (?, ?, ?, ?, NOW())
 `
  ;

/** all categories */
export const select_TB_COR_TALK_MST_01 =
  `SELECT SYSTEM_CODE, TALK_ID, TALK_NAME, CREATE_USER_ID
   FROM BRUNNER.TB_COR_TALK_MST
  WHERE SYSTEM_CODE=?
  ORDER BY CREATE_TIME DESC
 `
  ;

/** user's categories */
export const select_TB_COR_TALK_MST_02 =
  `SELECT SYSTEM_CODE, TALK_ID, TALK_NAME, CREATE_USER_ID
    FROM BRUNNER.TB_COR_TALK_MST
   WHERE SYSTEM_CODE=?
     AND TALK_ID LIKE ?
   ORDER BY CREATE_TIME DESC
  `
  ;

/** other's categories */
export const select_TB_COR_TALK_MST_03 =
  `SELECT SYSTEM_CODE, TALK_ID, TALK_NAME, CREATE_USER_ID
     FROM BRUNNER.TB_COR_TALK_MST
    WHERE SYSTEM_CODE=?
      AND TALK_ID NOT LIKE ?
    ORDER BY CREATE_TIME DESC
   `
  ;
